### PR TITLE
implimented and updated testing for 1.12.

### LINKED ISSUE #21: Compilation Error in 1.12.2
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project b173gen: Compilation failure: Compilation failure:
[ERROR] /mnt/c/Users/Kurisu/Minecraft/173generator/src/test/java/com/github/barteks2x/b173gen/test/fakeimpl/BukkitWorldStub.java:[22,7] error: BukkitWorldStub is not abstract and does not override abstract method playSound(Location,String,SoundCategory,float,float) in World
[ERROR]
[ERROR] /mnt/c/Users/Kurisu/Minecraft/173generator/src/test/java/com/github/barteks2x/b173gen/test/fakeimpl/BukkitChestStub.java:[16,0] error: BukkitChestStub is not abstract and does not override abstract method getSnapshotInventory() in Container
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

cc @coolsa

### PR DESCRIPTION
**Pull request by coolsa**
got the test packages compiling again. Updated pom to stop giving me a different error. Needed to make the setData override in the BukkitBlockStub test empty for it to stop throwing test errors. not sure if that needs a different test. also fixed a minor file leak to get it to compile on my computer.
fixes #21

### CODE REVIEW

File: src/test/java/com/github/barteks2x/b173gen/test/TestCompareToBetaTerrain.java [hunk 1]
```diff
@@ -103,6 +103,8 @@ private void doTest(IChunkModifier chunkModifier, String name, String dependency
         ChunkModifierTester.TestResults expectedRegults = new ChunkModifierTester.TestResults(MAX_DIFF);
 
         assertEquals("The generated world must be equal to saved world", expectedRegults, actualResults);
+        compare=null;
+        System.gc();
```
Comment (Barteks2x) [inline src/test/java/com/github/barteks2x/b173gen/test/TestCompareToBetaTerrain.java]: What is the point of that?

File: src/test/java/com/github/barteks2x/b173gen/test/fakeimpl/BukkitBlockStub.java [hunk 2]
```diff
@@ -157,11 +161,6 @@ public Chunk getChunk() {
     }
 
     @Override
-    public void setData(byte b) {
-        throw new UnsupportedOperationException();
-    }
```
Comment (Barteks2x) [inline src/test/java/com/github/barteks2x/b173gen/test/fakeimpl/BukkitBlockStub.java]: Why did you move this method up?
